spring:
  jpa:
    database: MYSQL
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect.storage_engine: innodb
      hibernate.generate_statistics: ${HIBERNATE_GENERATE_STATISTICS:false}
  datasource:
    hikari:
      maximum-pool-size: 3
  flyway:
    enabled: true
    locations: classpath:user/flyway/{vendor}
    table: flyway_schema_history_user
    encoding: UTF-8
    baseline-on-migrate: true
